<?php
if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

if($this->db->get_var("SHOW TABLES LIKE '{$this->custom_table}'") != $this->custom_table) {
			$charset_collate = $this->db->get_charset_collate();
			$sql = "CREATE TABLE `{$this->custom_table}` (
			  id INT(11) unsigned AUTO_INCREMENT PRIMARY KEY,
			  manufacturer text NOT NULL,
			  brand text NOT NULL,
			  model text NOT NULL,
			  _trim text NOT NULL,
			  generation  varchar(255) NOT NULL,
			  model_year  INT(11) NOT NULL,
			  years_built  varchar(255) NOT NULL,
			  production  varchar(255) NOT NULL,
			  presentation  varchar(255) NOT NULL,
			  designed_by  varchar(255) NOT NULL,
			  origin_country  varchar(255) NOT NULL,
			  segment  varchar(255) NOT NULL,
			  class  varchar(255) NOT NULL,
			  type text NOT NULL,
			  size  text NOT NULL,
			  size_2  text NOT NULL,
			  segment_1  text NOT NULL,
			  segment_2  text NOT NULL,
			  segment_3  text NOT NULL,
			  segment_4  text NOT NULL,
			  segment_5  text NOT NULL,
			  overall_length  text NOT NULL,
			  overall_width  text NOT NULL,
			  overall_height  varchar(255) NOT NULL,
			  wheelbase  varchar(255) NOT NULL,
			  front_track  varchar(255) NOT NULL,
			  rear_track  varchar(255) NOT NULL,
			  ground_clearance  varchar(255) NOT NULL,
			  front_overhang  varchar(255) NOT NULL,
			  rear_overhang  varchar(255) NOT NULL,
			  weight  varchar(255) NOT NULL,
			  distribution  varchar(255) NOT NULL,
			  structure  varchar(255) NOT NULL,
			  body  varchar(255) NOT NULL,
			  suspension_front varchar(255) NOT NULL,
			  suspension_rear  varchar(255) NOT NULL,
			  driven_wheels  varchar(255) NOT NULL,
			  esp  text NOT NULL,
			  brakes_front  varchar(255) NOT NULL,
			  brakes_rear  varchar(255) NOT NULL,
			  brakes_description  varchar(255) NOT NULL,
			  steering_type  varchar(255) NOT NULL,
			  turning_circle varchar(255) NOT NULL,
			  front_tire_size varchar(255) NOT NULL,
			  rear_tire_size  varchar(255) NOT NULL,
			  tire_type  varchar(255) NOT NULL,
			  front_wheel  varchar(255) NOT NULL,
			  rear_wheel  varchar(255) NOT NULL,
			  wheel_type  text NOT NULL,
			  rear_spoiler  text NOT NULL,
			  mirrors  text NOT NULL,
			  airbags  text NOT NULL,
			  engine_type  text NOT NULL,
			  aspiration  text NOT NULL,
			  position  text NOT NULL,
			  weight_distribution  text NOT NULL,
			  main_bearings  text NOT NULL,
			  displacement  text NOT NULL,
			  bore_stroke  text NOT NULL,
			  valve_gear  text NOT NULL,
			  valvetrain  text NOT NULL,
			  compression_ratio  text NOT NULL,
			  horsepower  text NOT NULL,
			  torque  text NOT NULL,
			  redline varchar(255) NOT NULL,
			  cooling_system text NOT NULL,
			  emission_control text NOT NULL,
			  ignition text NOT NULL,
			  engine_management varchar(255) NOT NULL,
			  electrical_system varchar(255) NOT NULL,
			  alternator varchar(255) NOT NULL,
			  fuel_system text NOT NULL,
			  fuel_type text NOT NULL,
			  fuel_consumption_mpg text NOT NULL,
			  lubrication text NOT NULL,
			  specific_output text NOT NULL,
			  power_weight_ratio text NOT NULL,
			  transmission_type text NOT NULL,
			  clutch text NOT NULL,
			  clutch_disc_diameter text NOT NULL,
			  transmission_1st_gear_ratio text NOT NULL,
			  transmission_2nd_gear_ratio text NOT NULL,
			  transmission_3rd_gear_ratio text NOT NULL,
			  transmission_4th_gear_ratio text NOT NULL,
			  transmission_5th_gear_ratio text NOT NULL,
			  transmission_6th_gear_ratio text NOT NULL,
			  reverse_gear_ratio text NOT NULL,
			  front_differential text NOT NULL,
			  rear_differential text NOT NULL,
			  capacities_fuel text NOT NULL,
			  engine_oil text NOT NULL,
			  capacities_cooling_system text NOT NULL,
			  luggage text NOT NULL,
			  us_msrp text NOT NULL,
			  eu_msrp text NOT NULL,
			  current_value text NOT NULL,
			  auction_history_value text NOT NULL,
			  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
			) $charset_collate;";
			require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
			dbDelta($sql);
}
if($this->db->get_var("SHOW TABLES LIKE '{$this->performance_custom_table}'") != $this->performance_custom_table) {
			$charset_collate = $this->db->get_charset_collate();
			$sql = "CREATE TABLE `{$this->performance_custom_table}` (
			  id INT(11) unsigned AUTO_INCREMENT PRIMARY KEY,
			  car_id  INT(11) NOT NULL,
			  top_speed_mph varchar(255) NOT NULL,
			  top_speed_kmph varchar(255) NOT NULL,
			  est_max_accelaration text NOT NULL,
			  performance_18m_slalom varchar(255) NOT NULL,
			  est_emissions  varchar(255) NOT NULL,
			  lateral_accelaration  varchar(255) NOT NULL,
			  acceleration_0_30_mph  varchar(255) NOT NULL,
			  acceleration_0_40_mph  varchar(255) NOT NULL,
			  acceleration_0_50_mph  varchar(255) NOT NULL,
			  acceleration_0_60_mph  varchar(255) NOT NULL,
			  acceleration_0_70_mph  varchar(255) NOT NULL,
			  acceleration_0_80_mph  varchar(255) NOT NULL,
			  acceleration_0_90_mph  varchar(255) NOT NULL,
			  acceleration_0_100_mph  varchar(255) NOT NULL,
			  acceleration_0_150_mph  varchar(255) NOT NULL,
			  acceleration_0_124_mph  varchar(255) NOT NULL,
			  acceleration_1_8_mile  varchar(255) NOT NULL,
			  acceleration_1_4_mile  varchar(255) NOT NULL,	
			  acceleration_1_2_mile  varchar(255) NOT NULL,	
			  acceleration_1_8_mile_time  varchar(255) NOT NULL,
			  acceleration_1_8_mile_speed  varchar(255) NOT NULL,
			  acceleration_1_4_mile_time  varchar(255) NOT NULL,	
			  acceleration_1_4_mile_speed  varchar(255) NOT NULL,
			  acceleration_1_2_mile_time  varchar(255) NOT NULL,
			  acceleration_1_2_mile_speed  varchar(255) NOT NULL,
			  acceleration_0_40_kmph  varchar(255) NOT NULL,
			  acceleration_0_50_kmph  varchar(255) NOT NULL,
			  acceleration_0_60_kmph  varchar(255) NOT NULL,
			  acceleration_0_70_kmph  varchar(255) NOT NULL,
			  acceleration_0_80_kmph  varchar(255) NOT NULL,
			  acceleration_0_90_kmph  varchar(255) NOT NULL,
			  acceleration_0_100_kmph  varchar(255) NOT NULL,
			  acceleration_0_120_kmph  varchar(255) NOT NULL,
			  acceleration_0_130_kmph  varchar(255) NOT NULL,
			  acceleration_0_140_kmph  varchar(255) NOT NULL,
			  acceleration_0_150_kmph  varchar(255) NOT NULL,
			  acceleration_0_160_kmph  varchar(255) NOT NULL,
			  acceleration_0_170_kmph  varchar(255) NOT NULL,
			  acceleration_0_180_kmph  varchar(255) NOT NULL,
			  acceleration_0_190_kmph  varchar(255) NOT NULL,
			  acceleration_0_200_kmph  varchar(255) NOT NULL,
			  acceleration_0_220_kmph  varchar(255) NOT NULL,
			  acceleration_0_250_kmph  varchar(255) NOT NULL,
			  acceleration_0_260_kmph  varchar(255) NOT NULL,
			  acceleration_0_270_kmph  varchar(255) NOT NULL,
			  acceleration_0_300_kmph  varchar(255) NOT NULL,
			  acceleration_1000m  varchar(255) NOT NULL,
			  braking_100_0_mph  varchar(255) NOT NULL,
			  braking_60_0_mph  varchar(255) NOT NULL,
			  braking_200_0_kmph  varchar(255) NOT NULL,
			  braking_100_0_kmph  varchar(255) NOT NULL,
			  rolling_acceleration_5_60_mph  varchar(255) NOT NULL,
			  rolling_acceleration_60_100_mph  varchar(255) NOT NULL,
			  rolling_acceleration_100_150_mph  varchar(255) NOT NULL,
			  rolling_acceleration_60_100_kmph  varchar(255) NOT NULL,
			  rolling_acceleration_100_200_kmph  varchar(255) NOT NULL,
			  rolling_acceleration_200_300_kmph  varchar(255) NOT NULL,
			  nurburgring_time  varchar(255) NOT NULL,
			  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
			) $charset_collate;";
			require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
			dbDelta($sql);
}
if($this->db->get_var("SHOW TABLES LIKE '{$this->shortcode_table}'") != $this->shortcode_table) {
	$charset_collate = $this->db->get_charset_collate();
			$sql = "CREATE TABLE `{$this->shortcode_table}` (
			  id INT(11) unsigned AUTO_INCREMENT PRIMARY KEY,
			  shortcode_name text NOT NULL,
			  auto_id INT(11) NOT NULL,
			  perf_id INT(11) NOT NULL,
			  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
			) $charset_collate;";
			require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
			dbDelta($sql);

}